name: omka2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_info: 0.3.0
  splashscreen:
  shared_preferences: 0.4.3
  sqflite:
  flutter_svg:
  rounded_modal:
  url_launcher: 4.1.0+1
  http:
  barcode_scan:
  flutter_local_notifications:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: ProductSans-Bold
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
    - family: ProductSans-Light
      fonts:
        - asset: assets/fonts/ProductSans-Light.ttf
    - family: ProductSans-Medium
      fonts:
        - asset: assets/fonts/ProductSans-Medium.ttf
    - family: ProductSans-Thin
      fonts:
        - asset: assets/fonts/ProductSans-Thin.ttf
    - family: ProductSans-Regular
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf

    - family: SFProText-Semibold
      fonts:
        - asset: assets/fonts/SFProText-Semibold.ttf
    - family: SFProText-Regular
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: SFProText-Medium
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/roman.jpg
    - assets/images/artem.jpg
    - assets/images/yana.jpg
    - assets/images/sberbank.jpg
    - assets/images/logo_omka.jpg
    - assets/svg/iconAdd.svg
    - assets/svg/logo_omka_orange.svg
    - assets/svg/logo_omka_red.svg
    - assets/svg/logo_omka_blue.svg
    - assets/svg/logo_omka_green.svg
    - assets/svg/logo.svg
    - assets/svg/logo_omka_add.svg
    - assets/svg/nfc-card.svg

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
